spring:
  datasource:
    password: Kangbh98!
    url: jdbc:mysql://localhost:3306/HackatonP?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 589018407552-o30r738n78kj1k5f7btcjjbmkdtkte1u.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - email
           - profile